server.port=8080

# Google Gemini Configuration
spring.ai.vertex.ai.gemini.project-id=gen-lang-client-0968280606
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash

# Vertex AI embedding model config
spring.ai.vertex.ai.embedding.project-id=gen-lang-client-0968280606
spring.ai.vertex.ai.embedding.location=us-central1
spring.ai.vertex.ai.embedding.model=textembedding-gecko@001

# Chroma Vector DB
spring.ai.vectorstore.chroma.initialize-schema=false
spring.ai.vectorstore.chroma.collection-name=genai

# Gemini with API Key
google.generative.language.uri=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
google.generative.language.api-key=AIzaSyDideVc2tucxyOgfWNCjDo7IRjwV3ETzN8

# Open AI API Key
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-3.5-turbo

# Disable security
spring.autoconfigure.exclude=\
    org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
    org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

# Logging config
logging.level.com.genia.app=DEBUG
logging.level.org.apache.lucene=DEBUG
logging.level.org.springframework.ai=DEBUG