# Google Gemini Configuration
spring.ai.vertex.ai.gemini.project-id=gen-lang-client-0968280606
# run : gcloud auth application-default login
spring.ai.vertex.ai.gemini.location=us-central1
  # e.g., us-central1 or europe-west1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash

# Vertex AI embedding model config
spring.ai.vertex.ai.embedding.project-id=gen-lang-client-0968280606
spring.ai.vertex.ai.embedding.location=us-central1
spring.ai.vertex.ai.embedding.model=textembedding-gecko@001

# MCP Server Configuration
# This is the port where your MCP server will expose its tools.
# The Spring AI client will connect to this.
spring.ai.mcp.port=8081

# Server Port for the main application (where your REST endpoint for chat will be)
server.port=8080
  # This is where you'll send your chat requests to

logging.level.com.genia.app=DEBUG
logging.level.org.apache.lucene=DEBUG

logging.level.org.springframework.ai=DEBUG
spring.autoconfigure.exclude=\
    org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
    org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration